language: java
sudo: false
script: mvn clean verify

notifications:
  email:
    - as173176m@student.etf.bg.ac.rs
  slack: zuehlke-rs:c0yRi4KBmJ46fpkCwDlz3E78

# https://docs.travis-ci.com/user/languages/java/